### ISSUE TITLE
文件编码格式问题

### ISSUE THREAD

**Issue by ytugj** [corruptbear/WeiboBot#4]
非常感谢作者大大的程序（鞠躬）！
遇到一个小问题，在Linux下open默认编码格式是UTF-8，爬取的内容没有问题；但是Windows下open的默认编码格式是gbk，写入的时候会报错"UnicodeEncodeError:'gbk' codec can't encode character '\U000lf97a' in position 0"，line574改为f = open(f"{uid}_{screen_name}.txt","w",encoding="utf-8")，line576改为f = open(f"{uid}.txt", "w",encoding="utf-8")后写入时就没有问题了。

**Comment by corruptbear** [comment]
谢谢指出！已修正。

p.s 默认编码应该不由操作系统类型直接决定，但是和系统locale设置/python相关设置有关系。总之直接指明编码是万全的
